# Generated by Django 4.2.30 on 2026-08-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0032_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecomment',
            name='courier_tracking_number',
            field=models.CharField(blank=True, default='', help_text='Courier/Tracking number', max_length=255),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='sample_submission_date',
            field=models.DateField(blank=True, help_text='Date sample was submitted', null=True),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'Revised Required')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='carton_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='carton_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='carton_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='gross_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='inspection_attempt',
            field=models.CharField(choices=[('1st', '1st Inspection'), ('2nd', '2nd Inspection'), ('3rd', '3rd Inspection')], default='1st', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='net_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='finalinspectionimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.template'),
        ),
        migrations.AlterField(
            model_name='samplecomment',
            name='sample_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Sample'), (2, '2nd Sample'), (3, '3rd Sample'), (4, '4th Sample'), (5, '5th Sample')], default=1),
        ),
        migrations.AlterField(
            model_name='samplecomment',
            name='sample_type',
            field=models.CharField(choices=[('Fit Sample', 'Fit Sample'), ('PP Sample', 'PP Sample'), ('Size Set', 'Size Set'), ('SMS', 'SMS'), ('Shipment Sample', 'Shipment Sample'), ('Proto', 'Proto')], max_length=50),
        ),
    ]
