# Generated by Django on 2026-08-31

from django.db import migrations


def resequence_sample_comments(apps, schema_editor):
    SampleComment = apps.get_model('qc', 'SampleComment')
    StyleMaster = apps.get_model('qc', 'StyleMaster')

    for style in StyleMaster.objects.all():
        # Find all distinct sample_types for this style
        sample_types = SampleComment.objects.filter(style=style).values_list('sample_type', flat=True).distinct()
        for stype in sample_types:
            comments = list(SampleComment.objects.filter(style=style, sample_type=stype).order_by('created_at'))
            for idx, comment in enumerate(comments, start=1):
                if comment.sample_number != idx:
                    comment.sample_number = idx
                    comment.save(update_fields=['sample_number'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0033_samplecomment_courier_tracking_number_and_more'),
    ]

    operations = [
        migrations.RunPython(resequence_sample_comments, reverse_noop),
    ]
