# Generated by Django 4.2.30 on 2026-08-31 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0034_resequence_sample_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.TextField(help_text='Comma-separated To: addresses')),
                ('cc', models.TextField(blank=True, help_text='Comma-separated CC: addresses')),
                ('subject', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('attachment_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Outbox',
                'verbose_name_plural': 'Email Outbox',
                'ordering': ['-created_at'],
            },
        ),
    ]
