# Generated by Django 4.2.30 on 2026-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0035_add_email_outbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalinspectionsizecheck',
            options={'ordering': ['color', 'size']},
        ),
        migrations.AddField(
            model_name='finalinspectionmeasurement',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finalinspectionsizecheck',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
