# Generated by Django 4.2.30 on 2026-09-03 01:21

from django.db import migrations, models
import django.db.models.deletion


def deduplicate_customer_emails(apps, schema_editor):
    CustomerEmail = apps.get_model('qc', 'CustomerEmail')
    seen = set()
    for ce in CustomerEmail.objects.all():
        key = (ce.customer_id, ce.email.strip().lower())
        if key in seen:
            ce.delete()
        else:
            seen.add(key)


def link_existing_styles(apps, schema_editor):
    StyleMaster = apps.get_model('qc', 'StyleMaster')
    Inspection = apps.get_model('qc', 'Inspection')
    FinalInspection = apps.get_model('qc', 'FinalInspection')

    styles = list(StyleMaster.objects.all())
    style_by_name = {s.style_name.strip().lower(): s for s in styles if s.style_name}
    style_by_po = {s.po_number.strip().lower(): s for s in styles if s.po_number}

    for ins in Inspection.objects.filter(style_master__isnull=True):
        style_key = (ins.style or '').strip().lower()
        po_key = (ins.po_number or '').strip().lower()
        matched = style_by_name.get(style_key) or style_by_po.get(po_key)
        if matched:
            ins.style_master = matched
            ins.save(update_fields=['style_master'])

    for fins in FinalInspection.objects.filter(style_master__isnull=True):
        style_key = (fins.style_no or '').strip().lower()
        po_key = (fins.order_no or '').strip().lower()
        matched = style_by_name.get(style_key) or style_by_po.get(po_key)
        if matched:
            fins.style_master = matched
            fins.save(update_fields=['style_master'])


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0037_factory_string_to_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='finalinspection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalinspection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalinspection',
            name='style_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_inspections', to='qc.stylemaster'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='style_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='qc.stylemaster'),
        ),
        migrations.RunPython(deduplicate_customer_emails, migrations.RunPython.noop),
        migrations.RunPython(link_existing_styles, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='customeremail',
            unique_together={('customer', 'email')},
        ),
        migrations.AddIndex(
            model_name='finalinspection',
            index=models.Index(fields=['-created_at'], name='qc_finalins_created_4c4961_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinspection',
            index=models.Index(fields=['order_no'], name='qc_finalins_order_n_e5bcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinspection',
            index=models.Index(fields=['result'], name='qc_finalins_result_4b6a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinspection',
            index=models.Index(fields=['inspection_date'], name='qc_finalins_inspect_5a1444_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinspection',
            index=models.Index(fields=['is_deleted'], name='qc_finalins_is_dele_45c704_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-created_at'], name='qc_inspecti_created_9cb0be_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['po_number'], name='qc_inspecti_po_numb_e86b48_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['stage'], name='qc_inspecti_stage_603c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['decision'], name='qc_inspecti_decisio_27b45e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['is_deleted'], name='qc_inspecti_is_dele_d9341c_idx'),
        ),
    ]
